theme: jekyll-theme-minimal
title: Iván Fernández Rojo
description: Bookmark this to keep an eye on the [Agile Software Development Model](https://ibanfr.github.io/agile-development-model/master/agile-software-development-model-for-product-feature-delivery/) updates!
