# Site settings
title: Iván Fernández Rojo
description: 'Business Card Page'
url: 'https://ibanfr.github.io'
baseurl: ''
profilepic: '/images/photo.jpg'
bkimage: '/images/bk1.jpg'
#google_analytics: UA-XXXXXX-X
font_awesome: 'd3b60fa2b5.js'

author:
  name: 'Iván Fernández'
  email: ivan.fernandez.rojo@gmail.com
#  mastodon: tzuehlke@mstdn.social
  twitter_username: Iban_FR
#  facebook_username: joshgerdes
  github_username:  ibanFR
  linkedin_username:  iván-fernández-rojo-a0987247
#  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
